name: Make fleet Video

on:
  push:
    branches:
      - master
    paths:
      - 'fleet-old/**'

jobs:
  call-workflow-passing-data:
    uses: shpwrck/rancher-training-material/.github/workflows/build-workflow.yml@master
    with:
      domain: fleet
    secrets:
      nara-token: ${{ secrets.NARAKEET_API_KEY }}
      gith-token: ${{ secrets.GITHUB_TOKEN }}
