name: Release Videos
on:
  push:
    tags:
    - v**
jobs:
  make_release_video:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        domain: [cluster-management, cluster-provisioning]
    steps:
    - uses: narakeet/build-video-github-action@v1.0.2
      id: video
      with:
        source-path: ${{ matrix.domain }}/script/source.md
        github-token: ${{ secrets.GITHUB_TOKEN }}
        api-key: ${{ secrets.NARAKEET_API_KEY }}
        result-file: ${{ matrix.domain }}.mp4
    - uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: "${{ steps.video.outputs.video-file }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
